Udělány menší úpravy + nová třída
jkremlacek/Holly pull request #1
Opened 2019-01-25 12:31 UTC by zafan

# Změny

* Pozměněn způsob získávání přihlašovacích údajů do Fedory
* `private String getImgAddressFromRels(String uuid)` **->** `public`
* Nástřel třídy pro práci s obrázky z imageserveru

2019-01-26 00:33 UTC, jkremlacek requested changes

2019-01-26 00:33 UTC, jkremlacek commented on src/main/java/cz/mzk/holly/extractor/ImageExtractor.java
> +        if (System.getenv("MZK_BASE").isEmpty()) {
je to detail, ale raději bych to pojmenoval BASE_PATH_MZK (a obdobně pro NDK), aby si to někdo v budoucnu nepletl s bázema mzk01 a mzk03

2019-01-26 00:33 UTC, jkremlacek commented on src/main/java/cz/mzk/holly/extractor/ImageExtractor.java
> +    private boolean isUuid(String uuid) {
Java na tohle myslí: 
```
try{
    UUID uuid = UUID.fromString(someUUID);
    //do something
} catch (IllegalArgumentException exception){
    //handle the case where string is not valid UUID 
}
```

2019-01-26 00:33 UTC, jkremlacek commented on src/main/java/cz/mzk/holly/fedora/FedoraRESTConnector.java
> +                String pw = System.getenv("FEDORA_PASSWORD");
toto je lepší načítat do statických konstant (neočekáváme, že bychom za běhu měnili systémovou proměnnou)

2019-01-26 00:37 UTC, jkremlacek commented on src/main/java/cz/mzk/holly/extractor/ImageExtractor.java
> +        if (System.getenv("MZK_BASE").isEmpty()) {
jinak kdybychom chtěli být jo poctiví, tak bychom báze měli předávat jako seznam možných cest (oddělených např středníkem v ENV)

2019-01-27 09:43 UTC, zafan commented on src/main/java/cz/mzk/holly/extractor/ImageExtractor.java
> +    private boolean isUuid(String uuid) {
V tomto případě to UUID není tak úplně UUID, resp. tahle metoda kontroluje jen jestli má správný prefix jakožto název Fedora objectu.

2019-01-27 16:36 UTC, jkremlacek commented on src/main/java/cz/mzk/holly/extractor/ImageExtractor.java
> +    private boolean isUuid(String uuid) {
pak bych to přejmenoval na hasUuidPrefix

2019-01-28 10:09 UTC, merged